DATA:
  data_dir: '/data/users/fu/big_motor_blendar_binlabel_npy'
  which_dataset: 'Motor_Dataset4'
  exp_name: 'STN_16_2048_100'
  num_segmentation_type: 2
  npoints: 2048

TRAIN:
  titel: 'binary_segmentation'
  train_stamp: 'train_on_sim'
  model: 'pct'
  train_batch_size: 8
  training: 1
  finetune: 0
  test: 0
  kernel_loss_weight: 0.05
  stn_loss_weight: 0.01
  epochs: 100
  use_class_weight: True
  screw_weight: 1.0
  use_sgd: 0
  lr: 0.01
  momentum: 0.9
  scheduler: 'cos'
  no_cuda: 0
  seed: 1
  dropout: 0.5
  emb_dims: 1024
  # k of knn
  k: 20
  validation_symbol: 'Validation'
  num_heads: 4
  num_attention_layer: 1
  self_encoder_latent_features: 128
  hidden_size_for_cross_attention: 512
  after_stn_as_input: 1
  after_stn_as_kernel_neighbor_query: 1

TEST:
  test_symbol: 'Train'
  test_batch_size: 16




